// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bigint.proto

/*
Package sonm is a generated protocol buffer package.

It is generated from these files:
	bigint.proto
	capabilities.proto
	container.proto
	deal.proto
	dwh.proto
	hub.proto
	insonmnia.proto
	locator.proto
	marketplace.proto
	miner.proto
	nat.proto
	net.proto
	node.proto
	order.proto
	rendezvous.proto
	timestamp.proto
	volume.proto

It has these top-level messages:
	BigInt
	Capabilities
	CPUDevice
	RAMDevice
	GPUDevice
	NetworkSpec
	Container
	Deal
	OrdersListRequest
	OrdersListReply
	DealsListRequest
	DealsListReply
	DealChangeRequestsReply
	DealChangeRequest
	ListReply
	HubStartTaskRequest
	HubStartTaskReply
	HubStatusReply
	DealRequest
	ApproveDealRequest
	GetDevicePropertiesReply
	SetDevicePropertiesRequest
	SlotsReply
	GetAllSlotsReply
	AddSlotRequest
	RemoveSlotRequest
	GetRegisteredWorkersReply
	TaskListReply
	CPUDeviceInfo
	GPUDeviceInfo
	DevicesReply
	InsertSlotRequest
	PullTaskRequest
	DealInfoReply
	Empty
	ID
	TaskID
	PingReply
	CPUUsage
	MemoryUsage
	NetworkUsage
	ResourceUsage
	InfoReply
	TaskStatusReply
	AvailableResources
	StatusMapReply
	ContainerRestartPolicy
	TaskLogsRequest
	TaskLogsChunk
	DiscoverHubRequest
	TaskResourceRequirements
	Chunk
	Progress
	AnnounceRequest
	ResolveRequest
	ResolveReply
	GetOrdersRequest
	GetOrdersReply
	GetProcessingReply
	TouchOrdersRequest
	MinerHandshakeRequest
	MinerHandshakeReply
	MinerStartRequest
	MinerStartReply
	TaskInfo
	Endpoints
	MinerStatusMapRequest
	SaveRequest
	Addr
	SocketAddr
	TaskListRequest
	DealListRequest
	DealListReply
	DealStatusReply
	Geo
	Resources
	Slot
	Order
	ConnectRequest
	PublishRequest
	RendezvousReply
	RendezvousState
	RendezvousMeeting
	ResolveMetaReply
	Timestamp
	Volume
*/
package sonm

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// BigInt represents multi-precision value stored as a big integer.
type BigInt struct {
	Neg bool   `protobuf:"varint,1,opt,name=neg" json:"neg,omitempty"`
	Abs []byte `protobuf:"bytes,2,opt,name=abs,proto3" json:"abs,omitempty"`
}

func (m *BigInt) Reset()                    { *m = BigInt{} }
func (m *BigInt) String() string            { return proto.CompactTextString(m) }
func (*BigInt) ProtoMessage()               {}
func (*BigInt) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BigInt) GetNeg() bool {
	if m != nil {
		return m.Neg
	}
	return false
}

func (m *BigInt) GetAbs() []byte {
	if m != nil {
		return m.Abs
	}
	return nil
}

func init() {
	proto.RegisterType((*BigInt)(nil), "sonm.BigInt")
}

func init() { proto.RegisterFile("bigint.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 88 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xca, 0x4c, 0xcf,
	0xcc, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x29, 0xce, 0xcf, 0xcb, 0x55, 0xd2,
	0xe1, 0x62, 0x73, 0xca, 0x4c, 0xf7, 0xcc, 0x2b, 0x11, 0x12, 0xe0, 0x62, 0xce, 0x4b, 0x4d, 0x97,
	0x60, 0x54, 0x60, 0xd4, 0xe0, 0x08, 0x02, 0x31, 0x41, 0x22, 0x89, 0x49, 0xc5, 0x12, 0x4c, 0x0a,
	0x8c, 0x1a, 0x3c, 0x41, 0x20, 0x66, 0x12, 0x1b, 0x58, 0xab, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff,
	0x52, 0x50, 0x08, 0x79, 0x4a, 0x00, 0x00, 0x00,
}
