// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dwh.proto

package sonm

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// grpccmd imports
import (
	"io"

	"github.com/spf13/cobra"
	"github.com/sshaman1101/grpccmd"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ComparisonOperator int32

const (
	ComparisonOperator_EQ  ComparisonOperator = 0
	ComparisonOperator_GTE ComparisonOperator = 1
	ComparisonOperator_LTE ComparisonOperator = 2
)

var ComparisonOperator_name = map[int32]string{
	0: "EQ",
	1: "GTE",
	2: "LTE",
}
var ComparisonOperator_value = map[string]int32{
	"EQ":  0,
	"GTE": 1,
	"LTE": 2,
}

func (x ComparisonOperator) String() string {
	return proto.EnumName(ComparisonOperator_name, int32(x))
}
func (ComparisonOperator) EnumDescriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

type OrdersListRequest struct {
	Type             OrderType          `protobuf:"varint,1,opt,name=type,enum=sonm.OrderType" json:"type,omitempty"`
	AuthorID         string             `protobuf:"bytes,2,opt,name=authorID" json:"authorID,omitempty"`
	CounterAgentID   string             `protobuf:"bytes,3,opt,name=counterAgentID" json:"counterAgentID,omitempty"`
	DurationSeconds  uint64             `protobuf:"varint,4,opt,name=durationSeconds" json:"durationSeconds,omitempty"`
	DurationOperator ComparisonOperator `protobuf:"varint,5,opt,name=durationOperator,enum=sonm.ComparisonOperator" json:"durationOperator,omitempty"`
	Price            uint64             `protobuf:"varint,6,opt,name=price" json:"price,omitempty"`
	PriceOperator    ComparisonOperator `protobuf:"varint,7,opt,name=priceOperator,enum=sonm.ComparisonOperator" json:"priceOperator,omitempty"`
	CpuCount         uint64             `protobuf:"varint,8,opt,name=cpuCount" json:"cpuCount,omitempty"`
	GpuCount         uint64             `protobuf:"varint,9,opt,name=gpuCount" json:"gpuCount,omitempty"`
	RamBytes         uint64             `protobuf:"varint,10,opt,name=ramBytes" json:"ramBytes,omitempty"`
	Limit            uint64             `protobuf:"varint,11,opt,name=limit" json:"limit,omitempty"`
	Offset           uint64             `protobuf:"varint,12,opt,name=offset" json:"offset,omitempty"`
}

func (m *OrdersListRequest) Reset()                    { *m = OrdersListRequest{} }
func (m *OrdersListRequest) String() string            { return proto.CompactTextString(m) }
func (*OrdersListRequest) ProtoMessage()               {}
func (*OrdersListRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *OrdersListRequest) GetType() OrderType {
	if m != nil {
		return m.Type
	}
	return OrderType_ANY
}

func (m *OrdersListRequest) GetAuthorID() string {
	if m != nil {
		return m.AuthorID
	}
	return ""
}

func (m *OrdersListRequest) GetCounterAgentID() string {
	if m != nil {
		return m.CounterAgentID
	}
	return ""
}

func (m *OrdersListRequest) GetDurationSeconds() uint64 {
	if m != nil {
		return m.DurationSeconds
	}
	return 0
}

func (m *OrdersListRequest) GetDurationOperator() ComparisonOperator {
	if m != nil {
		return m.DurationOperator
	}
	return ComparisonOperator_EQ
}

func (m *OrdersListRequest) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *OrdersListRequest) GetPriceOperator() ComparisonOperator {
	if m != nil {
		return m.PriceOperator
	}
	return ComparisonOperator_EQ
}

func (m *OrdersListRequest) GetCpuCount() uint64 {
	if m != nil {
		return m.CpuCount
	}
	return 0
}

func (m *OrdersListRequest) GetGpuCount() uint64 {
	if m != nil {
		return m.GpuCount
	}
	return 0
}

func (m *OrdersListRequest) GetRamBytes() uint64 {
	if m != nil {
		return m.RamBytes
	}
	return 0
}

func (m *OrdersListRequest) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *OrdersListRequest) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type OrdersListReply struct {
	Orders []*Order `protobuf:"bytes,1,rep,name=orders" json:"orders,omitempty"`
}

func (m *OrdersListReply) Reset()                    { *m = OrdersListReply{} }
func (m *OrdersListReply) String() string            { return proto.CompactTextString(m) }
func (*OrdersListReply) ProtoMessage()               {}
func (*OrdersListReply) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

func (m *OrdersListReply) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

type DealsListRequest struct {
	Status           DealStatus         `protobuf:"varint,3,opt,name=status,enum=sonm.DealStatus" json:"status,omitempty"`
	SupplierID       string             `protobuf:"bytes,1,opt,name=supplierID" json:"supplierID,omitempty"`
	ConsumerID       string             `protobuf:"bytes,2,opt,name=consumerID" json:"consumerID,omitempty"`
	DurationSeconds  uint64             `protobuf:"varint,4,opt,name=durationSeconds" json:"durationSeconds,omitempty"`
	DurationOperator ComparisonOperator `protobuf:"varint,5,opt,name=durationOperator,enum=sonm.ComparisonOperator" json:"durationOperator,omitempty"`
	Price            uint64             `protobuf:"varint,6,opt,name=price" json:"price,omitempty"`
	PriceOperator    ComparisonOperator `protobuf:"varint,7,opt,name=priceOperator,enum=sonm.ComparisonOperator" json:"priceOperator,omitempty"`
	Limit            uint64             `protobuf:"varint,8,opt,name=limit" json:"limit,omitempty"`
	Offset           uint64             `protobuf:"varint,9,opt,name=offset" json:"offset,omitempty"`
}

func (m *DealsListRequest) Reset()                    { *m = DealsListRequest{} }
func (m *DealsListRequest) String() string            { return proto.CompactTextString(m) }
func (*DealsListRequest) ProtoMessage()               {}
func (*DealsListRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{2} }

func (m *DealsListRequest) GetStatus() DealStatus {
	if m != nil {
		return m.Status
	}
	return DealStatus_ANY_STATUS
}

func (m *DealsListRequest) GetSupplierID() string {
	if m != nil {
		return m.SupplierID
	}
	return ""
}

func (m *DealsListRequest) GetConsumerID() string {
	if m != nil {
		return m.ConsumerID
	}
	return ""
}

func (m *DealsListRequest) GetDurationSeconds() uint64 {
	if m != nil {
		return m.DurationSeconds
	}
	return 0
}

func (m *DealsListRequest) GetDurationOperator() ComparisonOperator {
	if m != nil {
		return m.DurationOperator
	}
	return ComparisonOperator_EQ
}

func (m *DealsListRequest) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *DealsListRequest) GetPriceOperator() ComparisonOperator {
	if m != nil {
		return m.PriceOperator
	}
	return ComparisonOperator_EQ
}

func (m *DealsListRequest) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *DealsListRequest) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type DealsListReply struct {
	Deals []*Deal `protobuf:"bytes,1,rep,name=deals" json:"deals,omitempty"`
}

func (m *DealsListReply) Reset()                    { *m = DealsListReply{} }
func (m *DealsListReply) String() string            { return proto.CompactTextString(m) }
func (*DealsListReply) ProtoMessage()               {}
func (*DealsListReply) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{3} }

func (m *DealsListReply) GetDeals() []*Deal {
	if m != nil {
		return m.Deals
	}
	return nil
}

type DealChangeRequestsReply struct {
	ChangeRequests []*DealChangeRequest `protobuf:"bytes,1,rep,name=changeRequests" json:"changeRequests,omitempty"`
}

func (m *DealChangeRequestsReply) Reset()                    { *m = DealChangeRequestsReply{} }
func (m *DealChangeRequestsReply) String() string            { return proto.CompactTextString(m) }
func (*DealChangeRequestsReply) ProtoMessage()               {}
func (*DealChangeRequestsReply) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{4} }

func (m *DealChangeRequestsReply) GetChangeRequests() []*DealChangeRequest {
	if m != nil {
		return m.ChangeRequests
	}
	return nil
}

type DealChangeRequest struct {
	DurationSeconds uint64  `protobuf:"varint,1,opt,name=durationSeconds" json:"durationSeconds,omitempty"`
	Price           *BigInt `protobuf:"bytes,2,opt,name=price" json:"price,omitempty"`
}

func (m *DealChangeRequest) Reset()                    { *m = DealChangeRequest{} }
func (m *DealChangeRequest) String() string            { return proto.CompactTextString(m) }
func (*DealChangeRequest) ProtoMessage()               {}
func (*DealChangeRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{5} }

func (m *DealChangeRequest) GetDurationSeconds() uint64 {
	if m != nil {
		return m.DurationSeconds
	}
	return 0
}

func (m *DealChangeRequest) GetPrice() *BigInt {
	if m != nil {
		return m.Price
	}
	return nil
}

func init() {
	proto.RegisterType((*OrdersListRequest)(nil), "sonm.OrdersListRequest")
	proto.RegisterType((*OrdersListReply)(nil), "sonm.OrdersListReply")
	proto.RegisterType((*DealsListRequest)(nil), "sonm.DealsListRequest")
	proto.RegisterType((*DealsListReply)(nil), "sonm.DealsListReply")
	proto.RegisterType((*DealChangeRequestsReply)(nil), "sonm.DealChangeRequestsReply")
	proto.RegisterType((*DealChangeRequest)(nil), "sonm.DealChangeRequest")
	proto.RegisterEnum("sonm.ComparisonOperator", ComparisonOperator_name, ComparisonOperator_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for DWH service

type DWHClient interface {
	GetOrdersList(ctx context.Context, in *OrdersListRequest, opts ...grpc.CallOption) (*OrdersListReply, error)
	GetOrderDetails(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Order, error)
	GetDealsList(ctx context.Context, in *DealsListRequest, opts ...grpc.CallOption) (*DealsListReply, error)
	GetDealDetails(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Deal, error)
	GetDealChangeRequests(ctx context.Context, in *ID, opts ...grpc.CallOption) (*DealChangeRequestsReply, error)
}

type dWHClient struct {
	cc *grpc.ClientConn
}

func NewDWHClient(cc *grpc.ClientConn) DWHClient {
	return &dWHClient{cc}
}

func (c *dWHClient) GetOrdersList(ctx context.Context, in *OrdersListRequest, opts ...grpc.CallOption) (*OrdersListReply, error) {
	out := new(OrdersListReply)
	err := grpc.Invoke(ctx, "/sonm.DWH/GetOrdersList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dWHClient) GetOrderDetails(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Order, error) {
	out := new(Order)
	err := grpc.Invoke(ctx, "/sonm.DWH/GetOrderDetails", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dWHClient) GetDealsList(ctx context.Context, in *DealsListRequest, opts ...grpc.CallOption) (*DealsListReply, error) {
	out := new(DealsListReply)
	err := grpc.Invoke(ctx, "/sonm.DWH/GetDealsList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dWHClient) GetDealDetails(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Deal, error) {
	out := new(Deal)
	err := grpc.Invoke(ctx, "/sonm.DWH/GetDealDetails", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dWHClient) GetDealChangeRequests(ctx context.Context, in *ID, opts ...grpc.CallOption) (*DealChangeRequestsReply, error) {
	out := new(DealChangeRequestsReply)
	err := grpc.Invoke(ctx, "/sonm.DWH/GetDealChangeRequests", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DWH service

type DWHServer interface {
	GetOrdersList(context.Context, *OrdersListRequest) (*OrdersListReply, error)
	GetOrderDetails(context.Context, *ID) (*Order, error)
	GetDealsList(context.Context, *DealsListRequest) (*DealsListReply, error)
	GetDealDetails(context.Context, *ID) (*Deal, error)
	GetDealChangeRequests(context.Context, *ID) (*DealChangeRequestsReply, error)
}

func RegisterDWHServer(s *grpc.Server, srv DWHServer) {
	s.RegisterService(&_DWH_serviceDesc, srv)
}

func _DWH_GetOrdersList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrdersListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DWHServer).GetOrdersList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.DWH/GetOrdersList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DWHServer).GetOrdersList(ctx, req.(*OrdersListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DWH_GetOrderDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DWHServer).GetOrderDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.DWH/GetOrderDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DWHServer).GetOrderDetails(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _DWH_GetDealsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DealsListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DWHServer).GetDealsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.DWH/GetDealsList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DWHServer).GetDealsList(ctx, req.(*DealsListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DWH_GetDealDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DWHServer).GetDealDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.DWH/GetDealDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DWHServer).GetDealDetails(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _DWH_GetDealChangeRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DWHServer).GetDealChangeRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.DWH/GetDealChangeRequests",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DWHServer).GetDealChangeRequests(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

var _DWH_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sonm.DWH",
	HandlerType: (*DWHServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrdersList",
			Handler:    _DWH_GetOrdersList_Handler,
		},
		{
			MethodName: "GetOrderDetails",
			Handler:    _DWH_GetOrderDetails_Handler,
		},
		{
			MethodName: "GetDealsList",
			Handler:    _DWH_GetDealsList_Handler,
		},
		{
			MethodName: "GetDealDetails",
			Handler:    _DWH_GetDealDetails_Handler,
		},
		{
			MethodName: "GetDealChangeRequests",
			Handler:    _DWH_GetDealChangeRequests_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dwh.proto",
}

// Begin grpccmd
var _ = grpccmd.RunE

// DWH
var _DWHCmd = &cobra.Command{
	Use:   "dWH [method]",
	Short: "Subcommand for the DWH service.",
}

var _DWH_GetOrdersListCmd = &cobra.Command{
	Use:   "getOrdersList",
	Short: "Make the GetOrdersList method call, input-type: sonm.OrdersListRequest output-type: sonm.OrdersListReply",
	RunE: grpccmd.RunE(
		"GetOrdersList",
		"sonm.OrdersListRequest",
		func(c io.Closer) interface{} {
			cc := c.(*grpc.ClientConn)
			return NewDWHClient(cc)
		},
	),
}

var _DWH_GetOrdersListCmd_gen = &cobra.Command{
	Use:   "getOrdersList-gen",
	Short: "Generate JSON for method call of GetOrdersList (input-type: sonm.OrdersListRequest)",
	RunE:  grpccmd.TypeToJson("sonm.OrdersListRequest"),
}

var _DWH_GetOrderDetailsCmd = &cobra.Command{
	Use:   "getOrderDetails",
	Short: "Make the GetOrderDetails method call, input-type: sonm.ID output-type: sonm.Order",
	RunE: grpccmd.RunE(
		"GetOrderDetails",
		"sonm.ID",
		func(c io.Closer) interface{} {
			cc := c.(*grpc.ClientConn)
			return NewDWHClient(cc)
		},
	),
}

var _DWH_GetOrderDetailsCmd_gen = &cobra.Command{
	Use:   "getOrderDetails-gen",
	Short: "Generate JSON for method call of GetOrderDetails (input-type: sonm.ID)",
	RunE:  grpccmd.TypeToJson("sonm.ID"),
}

var _DWH_GetDealsListCmd = &cobra.Command{
	Use:   "getDealsList",
	Short: "Make the GetDealsList method call, input-type: sonm.DealsListRequest output-type: sonm.DealsListReply",
	RunE: grpccmd.RunE(
		"GetDealsList",
		"sonm.DealsListRequest",
		func(c io.Closer) interface{} {
			cc := c.(*grpc.ClientConn)
			return NewDWHClient(cc)
		},
	),
}

var _DWH_GetDealsListCmd_gen = &cobra.Command{
	Use:   "getDealsList-gen",
	Short: "Generate JSON for method call of GetDealsList (input-type: sonm.DealsListRequest)",
	RunE:  grpccmd.TypeToJson("sonm.DealsListRequest"),
}

var _DWH_GetDealDetailsCmd = &cobra.Command{
	Use:   "getDealDetails",
	Short: "Make the GetDealDetails method call, input-type: sonm.ID output-type: sonm.Deal",
	RunE: grpccmd.RunE(
		"GetDealDetails",
		"sonm.ID",
		func(c io.Closer) interface{} {
			cc := c.(*grpc.ClientConn)
			return NewDWHClient(cc)
		},
	),
}

var _DWH_GetDealDetailsCmd_gen = &cobra.Command{
	Use:   "getDealDetails-gen",
	Short: "Generate JSON for method call of GetDealDetails (input-type: sonm.ID)",
	RunE:  grpccmd.TypeToJson("sonm.ID"),
}

var _DWH_GetDealChangeRequestsCmd = &cobra.Command{
	Use:   "getDealChangeRequests",
	Short: "Make the GetDealChangeRequests method call, input-type: sonm.ID output-type: sonm.DealChangeRequestsReply",
	RunE: grpccmd.RunE(
		"GetDealChangeRequests",
		"sonm.ID",
		func(c io.Closer) interface{} {
			cc := c.(*grpc.ClientConn)
			return NewDWHClient(cc)
		},
	),
}

var _DWH_GetDealChangeRequestsCmd_gen = &cobra.Command{
	Use:   "getDealChangeRequests-gen",
	Short: "Generate JSON for method call of GetDealChangeRequests (input-type: sonm.ID)",
	RunE:  grpccmd.TypeToJson("sonm.ID"),
}

// Register commands with the root command and service command
func init() {
	grpccmd.RegisterServiceCmd(_DWHCmd)
	_DWHCmd.AddCommand(
		_DWH_GetOrdersListCmd,
		_DWH_GetOrdersListCmd_gen,
		_DWH_GetOrderDetailsCmd,
		_DWH_GetOrderDetailsCmd_gen,
		_DWH_GetDealsListCmd,
		_DWH_GetDealsListCmd_gen,
		_DWH_GetDealDetailsCmd,
		_DWH_GetDealDetailsCmd_gen,
		_DWH_GetDealChangeRequestsCmd,
		_DWH_GetDealChangeRequestsCmd_gen,
	)
}

// End grpccmd

func init() { proto.RegisterFile("dwh.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 610 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x94, 0xdf, 0x6a, 0xdb, 0x3e,
	0x14, 0xc7, 0xe3, 0x24, 0x4d, 0x93, 0x93, 0x34, 0x71, 0x45, 0xff, 0x88, 0xc0, 0xef, 0x47, 0x70,
	0x61, 0x98, 0x5e, 0xe4, 0xc2, 0x83, 0x5d, 0x76, 0xb4, 0x75, 0xe9, 0x02, 0x85, 0x32, 0xb7, 0x30,
	0xd8, 0x9d, 0xea, 0xa8, 0xae, 0xc0, 0xb1, 0x3c, 0x4b, 0x66, 0xe4, 0x75, 0xf6, 0x2c, 0x7b, 0xa0,
	0x3d, 0xc2, 0x90, 0x64, 0xc7, 0x76, 0xdd, 0xb1, 0xfb, 0xdd, 0xe9, 0x7c, 0xbf, 0xe7, 0x8f, 0x72,
	0x3e, 0x72, 0x60, 0xb4, 0xfe, 0xfe, 0xb2, 0x4c, 0x33, 0x2e, 0x39, 0xea, 0x0b, 0x9e, 0x6c, 0xe6,
	0x93, 0x27, 0x16, 0xb1, 0x44, 0x1a, 0x6d, 0x0e, 0x6b, 0x4a, 0xe2, 0xe2, 0x3c, 0x63, 0x89, 0xca,
	0x48, 0x18, 0x29, 0x84, 0x31, 0xcf, 0xd6, 0x34, 0x33, 0x81, 0xf3, 0xb3, 0x07, 0x87, 0xf7, 0x2a,
	0x16, 0x77, 0x4c, 0xc8, 0x80, 0x7e, 0xcb, 0xa9, 0x90, 0xe8, 0x0c, 0xfa, 0x72, 0x9b, 0x52, 0x6c,
	0x2d, 0x2c, 0x77, 0xea, 0xcd, 0x96, 0xaa, 0xc1, 0x52, 0xa7, 0x3d, 0x6e, 0x53, 0x1a, 0x68, 0x13,
	0xcd, 0x61, 0x48, 0x72, 0xf9, 0xc2, 0xb3, 0x95, 0x8f, 0xbb, 0x0b, 0xcb, 0x1d, 0x05, 0xbb, 0x18,
	0xbd, 0x83, 0x69, 0xc8, 0xf3, 0x44, 0xd2, 0xec, 0x32, 0xa2, 0x89, 0x5c, 0xf9, 0xb8, 0xa7, 0x33,
	0x5e, 0xa9, 0xc8, 0x85, 0xd9, 0x3a, 0xcf, 0x88, 0x64, 0x3c, 0x79, 0xa0, 0x21, 0x4f, 0xd6, 0x02,
	0xf7, 0x17, 0x96, 0xdb, 0x0f, 0x5e, 0xcb, 0xc8, 0x07, 0xbb, 0x94, 0xee, 0x53, 0x9a, 0x11, 0xc9,
	0x33, 0xbc, 0xa7, 0xaf, 0x87, 0xcd, 0xf5, 0xae, 0xf9, 0x26, 0x25, 0x19, 0x13, 0x95, 0x1f, 0xb4,
	0x2a, 0xd0, 0x11, 0xec, 0xa5, 0x19, 0x0b, 0x29, 0x1e, 0xe8, 0x29, 0x26, 0x40, 0x17, 0x70, 0xa0,
	0x0f, 0xbb, 0xc6, 0xfb, 0x7f, 0x69, 0xdc, 0x4c, 0x57, 0x9b, 0x08, 0xd3, 0xfc, 0x5a, 0xfd, 0x34,
	0x3c, 0xd4, 0x8d, 0x77, 0xb1, 0xf2, 0xa2, 0xd2, 0x1b, 0x19, 0x2f, 0xaa, 0x79, 0x19, 0xd9, 0x5c,
	0x6d, 0x25, 0x15, 0x18, 0x8c, 0x57, 0xc6, 0xea, 0xa6, 0x31, 0xdb, 0x30, 0x89, 0xc7, 0xe6, 0xa6,
	0x3a, 0x40, 0x27, 0x30, 0xe0, 0xcf, 0xcf, 0x82, 0x4a, 0x3c, 0xd1, 0x72, 0x11, 0x39, 0x1f, 0x60,
	0x56, 0xa7, 0x98, 0xc6, 0x5b, 0x74, 0x06, 0x03, 0x0d, 0x5a, 0x60, 0x6b, 0xd1, 0x73, 0xc7, 0xde,
	0xb8, 0x46, 0x31, 0x28, 0x2c, 0xe7, 0x57, 0x17, 0x6c, 0x9f, 0x92, 0xb8, 0x41, 0xdf, 0x85, 0x81,
	0x90, 0x44, 0xe6, 0x42, 0x43, 0x9b, 0x7a, 0xb6, 0xa9, 0x54, 0x79, 0x0f, 0x5a, 0x0f, 0x0a, 0x1f,
	0xfd, 0x0f, 0x20, 0xf2, 0x34, 0x8d, 0x19, 0x55, 0x8f, 0xc0, 0xd2, 0x88, 0x6b, 0x8a, 0xf2, 0x43,
	0x9e, 0x88, 0x7c, 0x43, 0xab, 0x47, 0x52, 0x53, 0xfe, 0x11, 0xfc, 0x3b, 0x54, 0xc3, 0xb7, 0x51,
	0x8d, 0x1a, 0xa8, 0x3c, 0x98, 0xd6, 0x36, 0xae, 0x48, 0x2d, 0x60, 0x4f, 0x7d, 0xaf, 0x25, 0x28,
	0xa8, 0xd6, 0x1d, 0x18, 0xc3, 0xf9, 0x0a, 0xa7, 0x2a, 0xbc, 0x7e, 0x21, 0x49, 0x44, 0x0b, 0x4c,
	0xc2, 0x14, 0x7f, 0x84, 0x69, 0xd8, 0x90, 0x8b, 0x2e, 0xa7, 0x55, 0x97, 0x46, 0x59, 0xf0, 0x2a,
	0xdd, 0x21, 0x70, 0xd8, 0x4a, 0x7a, 0x0b, 0x8c, 0xf5, 0x36, 0x18, 0xa7, 0x5c, 0xa9, 0xa2, 0x3b,
	0xf6, 0x26, 0x66, 0xec, 0x15, 0x8b, 0x56, 0x89, 0x2c, 0x16, 0x7c, 0xbe, 0x04, 0xd4, 0xde, 0x22,
	0x1a, 0x40, 0xf7, 0xe6, 0xb3, 0xdd, 0x41, 0xfb, 0xd0, 0xbb, 0x7d, 0xbc, 0xb1, 0x2d, 0x75, 0xb8,
	0x7b, 0xbc, 0xb1, 0xbb, 0xde, 0x8f, 0x2e, 0xf4, 0xfc, 0x2f, 0x9f, 0xd0, 0x25, 0x1c, 0xdc, 0x52,
	0x59, 0x3d, 0x6c, 0x74, 0x5a, 0x7b, 0xc3, 0xf5, 0x27, 0x3b, 0x3f, 0x6e, 0x1b, 0x69, 0xbc, 0x75,
	0x3a, 0xe8, 0x1c, 0x66, 0x65, 0x0b, 0x9f, 0x4a, 0xc2, 0x62, 0x81, 0x86, 0x26, 0x77, 0xe5, 0xcf,
	0xeb, 0x9f, 0x84, 0xd3, 0x41, 0x17, 0x30, 0xb9, 0xa5, 0x72, 0x07, 0x07, 0x9d, 0x54, 0x2b, 0x6c,
	0x0c, 0x3b, 0x6a, 0xe9, 0x66, 0x96, 0x0b, 0xd3, 0xa2, 0xbe, 0x3d, 0xaa, 0x06, 0xd5, 0xe9, 0xa0,
	0x2b, 0x38, 0x2e, 0x32, 0x9b, 0x48, 0x6b, 0x05, 0xff, 0xfd, 0x81, 0x9f, 0x28, 0xa6, 0x3d, 0x0d,
	0xf4, 0x1f, 0xf8, 0xfb, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x02, 0x5d, 0x36, 0xc5, 0x0b, 0x06,
	0x00, 0x00,
}
