// Code generated by protoc-gen-go. DO NOT EDIT.
// source: marketplace.proto

package sonm

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// grpccmd imports
import (
	"io"

	"github.com/spf13/cobra"
	"github.com/sshaman1101/grpccmd"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type GetOrdersRequest struct {
	// Order keeps slot and type for searching
	Order *Order `protobuf:"bytes,1,opt,name=order" json:"order,omitempty"`
	// Count describe how namy results must be returned (order by price)
	Count uint64 `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
}

func (m *GetOrdersRequest) Reset()                    { *m = GetOrdersRequest{} }
func (m *GetOrdersRequest) String() string            { return proto.CompactTextString(m) }
func (*GetOrdersRequest) ProtoMessage()               {}
func (*GetOrdersRequest) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{0} }

func (m *GetOrdersRequest) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

func (m *GetOrdersRequest) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetOrdersReply struct {
	Orders []*Order `protobuf:"bytes,1,rep,name=orders" json:"orders,omitempty"`
}

func (m *GetOrdersReply) Reset()                    { *m = GetOrdersReply{} }
func (m *GetOrdersReply) String() string            { return proto.CompactTextString(m) }
func (*GetOrdersReply) ProtoMessage()               {}
func (*GetOrdersReply) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{1} }

func (m *GetOrdersReply) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

// GetProcessingReply represent Node's local
// orders processing status
type GetProcessingReply struct {
	Orders map[string]*GetProcessingReply_ProcessedOrder `protobuf:"bytes,2,rep,name=orders" json:"orders,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *GetProcessingReply) Reset()                    { *m = GetProcessingReply{} }
func (m *GetProcessingReply) String() string            { return proto.CompactTextString(m) }
func (*GetProcessingReply) ProtoMessage()               {}
func (*GetProcessingReply) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{2} }

func (m *GetProcessingReply) GetOrders() map[string]*GetProcessingReply_ProcessedOrder {
	if m != nil {
		return m.Orders
	}
	return nil
}

type GetProcessingReply_ProcessedOrder struct {
	Id        string     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Status    uint32     `protobuf:"varint,2,opt,name=status" json:"status,omitempty"`
	Timestamp *Timestamp `protobuf:"bytes,3,opt,name=timestamp" json:"timestamp,omitempty"`
	Extra     string     `protobuf:"bytes,4,opt,name=extra" json:"extra,omitempty"`
}

func (m *GetProcessingReply_ProcessedOrder) Reset()         { *m = GetProcessingReply_ProcessedOrder{} }
func (m *GetProcessingReply_ProcessedOrder) String() string { return proto.CompactTextString(m) }
func (*GetProcessingReply_ProcessedOrder) ProtoMessage()    {}
func (*GetProcessingReply_ProcessedOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor8, []int{2, 0}
}

func (m *GetProcessingReply_ProcessedOrder) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetProcessingReply_ProcessedOrder) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetProcessingReply_ProcessedOrder) GetTimestamp() *Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *GetProcessingReply_ProcessedOrder) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

type TouchOrdersRequest struct {
	IDs []string `protobuf:"bytes,1,rep,name=IDs" json:"IDs,omitempty"`
}

func (m *TouchOrdersRequest) Reset()                    { *m = TouchOrdersRequest{} }
func (m *TouchOrdersRequest) String() string            { return proto.CompactTextString(m) }
func (*TouchOrdersRequest) ProtoMessage()               {}
func (*TouchOrdersRequest) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{3} }

func (m *TouchOrdersRequest) GetIDs() []string {
	if m != nil {
		return m.IDs
	}
	return nil
}

func init() {
	proto.RegisterType((*GetOrdersRequest)(nil), "sonm.GetOrdersRequest")
	proto.RegisterType((*GetOrdersReply)(nil), "sonm.GetOrdersReply")
	proto.RegisterType((*GetProcessingReply)(nil), "sonm.GetProcessingReply")
	proto.RegisterType((*GetProcessingReply_ProcessedOrder)(nil), "sonm.GetProcessingReply.ProcessedOrder")
	proto.RegisterType((*TouchOrdersRequest)(nil), "sonm.TouchOrdersRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Market service

type MarketClient interface {
	GetOrders(ctx context.Context, in *GetOrdersRequest, opts ...grpc.CallOption) (*GetOrdersReply, error)
	GetOrderByID(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Order, error)
	CreateOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*Order, error)
	CancelOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*Empty, error)
	TouchOrders(ctx context.Context, in *TouchOrdersRequest, opts ...grpc.CallOption) (*Empty, error)
	// GetProcessing returns currently processing orders
	// not required in Marketplace service
	// must be implemented on Node
	GetProcessing(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetProcessingReply, error)
}

type marketClient struct {
	cc *grpc.ClientConn
}

func NewMarketClient(cc *grpc.ClientConn) MarketClient {
	return &marketClient{cc}
}

func (c *marketClient) GetOrders(ctx context.Context, in *GetOrdersRequest, opts ...grpc.CallOption) (*GetOrdersReply, error) {
	out := new(GetOrdersReply)
	err := grpc.Invoke(ctx, "/sonm.Market/GetOrders", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) GetOrderByID(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Order, error) {
	out := new(Order)
	err := grpc.Invoke(ctx, "/sonm.Market/GetOrderByID", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) CreateOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*Order, error) {
	out := new(Order)
	err := grpc.Invoke(ctx, "/sonm.Market/CreateOrder", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) CancelOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/sonm.Market/CancelOrder", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) TouchOrders(ctx context.Context, in *TouchOrdersRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/sonm.Market/TouchOrders", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) GetProcessing(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetProcessingReply, error) {
	out := new(GetProcessingReply)
	err := grpc.Invoke(ctx, "/sonm.Market/GetProcessing", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Market service

type MarketServer interface {
	GetOrders(context.Context, *GetOrdersRequest) (*GetOrdersReply, error)
	GetOrderByID(context.Context, *ID) (*Order, error)
	CreateOrder(context.Context, *Order) (*Order, error)
	CancelOrder(context.Context, *Order) (*Empty, error)
	TouchOrders(context.Context, *TouchOrdersRequest) (*Empty, error)
	// GetProcessing returns currently processing orders
	// not required in Marketplace service
	// must be implemented on Node
	GetProcessing(context.Context, *Empty) (*GetProcessingReply, error)
}

func RegisterMarketServer(s *grpc.Server, srv MarketServer) {
	s.RegisterService(&_Market_serviceDesc, srv)
}

func _Market_GetOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).GetOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.Market/GetOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).GetOrders(ctx, req.(*GetOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_GetOrderByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).GetOrderByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.Market/GetOrderByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).GetOrderByID(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Order)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.Market/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).CreateOrder(ctx, req.(*Order))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Order)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.Market/CancelOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).CancelOrder(ctx, req.(*Order))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_TouchOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TouchOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).TouchOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.Market/TouchOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).TouchOrders(ctx, req.(*TouchOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_GetProcessing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).GetProcessing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.Market/GetProcessing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).GetProcessing(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Market_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sonm.Market",
	HandlerType: (*MarketServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrders",
			Handler:    _Market_GetOrders_Handler,
		},
		{
			MethodName: "GetOrderByID",
			Handler:    _Market_GetOrderByID_Handler,
		},
		{
			MethodName: "CreateOrder",
			Handler:    _Market_CreateOrder_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _Market_CancelOrder_Handler,
		},
		{
			MethodName: "TouchOrders",
			Handler:    _Market_TouchOrders_Handler,
		},
		{
			MethodName: "GetProcessing",
			Handler:    _Market_GetProcessing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "marketplace.proto",
}

// Begin grpccmd
var _ = grpccmd.RunE

// Market
var _MarketCmd = &cobra.Command{
	Use:   "market [method]",
	Short: "Subcommand for the Market service.",
}

var _Market_GetOrdersCmd = &cobra.Command{
	Use:   "getOrders",
	Short: "Make the GetOrders method call, input-type: sonm.GetOrdersRequest output-type: sonm.GetOrdersReply",
	RunE: grpccmd.RunE(
		"GetOrders",
		"sonm.GetOrdersRequest",
		func(c io.Closer) interface{} {
			cc := c.(*grpc.ClientConn)
			return NewMarketClient(cc)
		},
	),
}

var _Market_GetOrdersCmd_gen = &cobra.Command{
	Use:   "getOrders-gen",
	Short: "Generate JSON for method call of GetOrders (input-type: sonm.GetOrdersRequest)",
	RunE:  grpccmd.TypeToJson("sonm.GetOrdersRequest"),
}

var _Market_GetOrderByIDCmd = &cobra.Command{
	Use:   "getOrderByID",
	Short: "Make the GetOrderByID method call, input-type: sonm.ID output-type: sonm.Order",
	RunE: grpccmd.RunE(
		"GetOrderByID",
		"sonm.ID",
		func(c io.Closer) interface{} {
			cc := c.(*grpc.ClientConn)
			return NewMarketClient(cc)
		},
	),
}

var _Market_GetOrderByIDCmd_gen = &cobra.Command{
	Use:   "getOrderByID-gen",
	Short: "Generate JSON for method call of GetOrderByID (input-type: sonm.ID)",
	RunE:  grpccmd.TypeToJson("sonm.ID"),
}

var _Market_CreateOrderCmd = &cobra.Command{
	Use:   "createOrder",
	Short: "Make the CreateOrder method call, input-type: sonm.Order output-type: sonm.Order",
	RunE: grpccmd.RunE(
		"CreateOrder",
		"sonm.Order",
		func(c io.Closer) interface{} {
			cc := c.(*grpc.ClientConn)
			return NewMarketClient(cc)
		},
	),
}

var _Market_CreateOrderCmd_gen = &cobra.Command{
	Use:   "createOrder-gen",
	Short: "Generate JSON for method call of CreateOrder (input-type: sonm.Order)",
	RunE:  grpccmd.TypeToJson("sonm.Order"),
}

var _Market_CancelOrderCmd = &cobra.Command{
	Use:   "cancelOrder",
	Short: "Make the CancelOrder method call, input-type: sonm.Order output-type: sonm.Empty",
	RunE: grpccmd.RunE(
		"CancelOrder",
		"sonm.Order",
		func(c io.Closer) interface{} {
			cc := c.(*grpc.ClientConn)
			return NewMarketClient(cc)
		},
	),
}

var _Market_CancelOrderCmd_gen = &cobra.Command{
	Use:   "cancelOrder-gen",
	Short: "Generate JSON for method call of CancelOrder (input-type: sonm.Order)",
	RunE:  grpccmd.TypeToJson("sonm.Order"),
}

var _Market_TouchOrdersCmd = &cobra.Command{
	Use:   "touchOrders",
	Short: "Make the TouchOrders method call, input-type: sonm.TouchOrdersRequest output-type: sonm.Empty",
	RunE: grpccmd.RunE(
		"TouchOrders",
		"sonm.TouchOrdersRequest",
		func(c io.Closer) interface{} {
			cc := c.(*grpc.ClientConn)
			return NewMarketClient(cc)
		},
	),
}

var _Market_TouchOrdersCmd_gen = &cobra.Command{
	Use:   "touchOrders-gen",
	Short: "Generate JSON for method call of TouchOrders (input-type: sonm.TouchOrdersRequest)",
	RunE:  grpccmd.TypeToJson("sonm.TouchOrdersRequest"),
}

var _Market_GetProcessingCmd = &cobra.Command{
	Use:   "getProcessing",
	Short: "Make the GetProcessing method call, input-type: sonm.Empty output-type: sonm.GetProcessingReply",
	RunE: grpccmd.RunE(
		"GetProcessing",
		"sonm.Empty",
		func(c io.Closer) interface{} {
			cc := c.(*grpc.ClientConn)
			return NewMarketClient(cc)
		},
	),
}

var _Market_GetProcessingCmd_gen = &cobra.Command{
	Use:   "getProcessing-gen",
	Short: "Generate JSON for method call of GetProcessing (input-type: sonm.Empty)",
	RunE:  grpccmd.TypeToJson("sonm.Empty"),
}

// Register commands with the root command and service command
func init() {
	grpccmd.RegisterServiceCmd(_MarketCmd)
	_MarketCmd.AddCommand(
		_Market_GetOrdersCmd,
		_Market_GetOrdersCmd_gen,
		_Market_GetOrderByIDCmd,
		_Market_GetOrderByIDCmd_gen,
		_Market_CreateOrderCmd,
		_Market_CreateOrderCmd_gen,
		_Market_CancelOrderCmd,
		_Market_CancelOrderCmd_gen,
		_Market_TouchOrdersCmd,
		_Market_TouchOrdersCmd_gen,
		_Market_GetProcessingCmd,
		_Market_GetProcessingCmd_gen,
	)
}

// End grpccmd

func init() { proto.RegisterFile("marketplace.proto", fileDescriptor8) }

var fileDescriptor8 = []byte{
	// 429 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x8d, 0x9d, 0xc4, 0xc2, 0x63, 0x9a, 0x86, 0x51, 0x55, 0x59, 0x3e, 0x05, 0x83, 0x68, 0x39,
	0x90, 0x43, 0x10, 0xa8, 0xe2, 0xe3, 0x02, 0xa9, 0xaa, 0x08, 0x21, 0xd0, 0xaa, 0x7f, 0x60, 0x6b,
	0x8f, 0xc0, 0xaa, 0xbf, 0xd8, 0x5d, 0x23, 0x7c, 0xe0, 0x67, 0xc1, 0xef, 0x43, 0xde, 0xb5, 0x8d,
	0xdd, 0x34, 0xb7, 0x9d, 0x37, 0xef, 0xbd, 0xc9, 0xbc, 0x89, 0xe1, 0x51, 0xc6, 0xc5, 0x2d, 0xa9,
	0x32, 0xe5, 0x11, 0xad, 0x4b, 0x51, 0xa8, 0x02, 0x67, 0xb2, 0xc8, 0xb3, 0xc0, 0x2b, 0x44, 0x4c,
	0xc2, 0x40, 0xc1, 0x71, 0x92, 0x37, 0x60, 0x9e, 0xf0, 0x0e, 0x50, 0x49, 0x46, 0x52, 0xf1, 0xac,
	0x34, 0x40, 0xf8, 0x09, 0x96, 0x57, 0xa4, 0xbe, 0x34, 0x1a, 0xc9, 0xe8, 0x47, 0x45, 0x52, 0xe1,
	0x63, 0x98, 0x6b, 0x13, 0xdf, 0x5a, 0x59, 0xe7, 0xde, 0xc6, 0x5b, 0x37, 0x1e, 0x6b, 0xcd, 0x61,
	0xa6, 0x83, 0x27, 0x30, 0x8f, 0x8a, 0x2a, 0x57, 0xbe, 0xbd, 0xb2, 0xce, 0x67, 0xcc, 0x14, 0xe1,
	0x2b, 0x58, 0x0c, 0xcc, 0xca, 0xb4, 0xc6, 0x27, 0xe0, 0x68, 0x81, 0xf4, 0xad, 0xd5, 0xf4, 0xae,
	0x57, 0xdb, 0x0a, 0xff, 0xd8, 0x80, 0x57, 0xa4, 0xbe, 0x8a, 0x22, 0x22, 0x29, 0x93, 0xfc, 0x9b,
	0xd1, 0xbe, 0xeb, 0xb5, 0xb6, 0xd6, 0x3e, 0x35, 0xda, 0x7d, 0xa6, 0xb1, 0x93, 0x97, 0xb9, 0x12,
	0x75, 0x67, 0x1a, 0xfc, 0x86, 0x45, 0x4b, 0xa3, 0x58, 0xf7, 0x71, 0x01, 0x76, 0x12, 0xeb, 0x9d,
	0x5c, 0x66, 0x27, 0x31, 0x9e, 0x82, 0x23, 0x15, 0x57, 0x95, 0xd4, 0x4b, 0x1c, 0xb1, 0xb6, 0xc2,
	0x17, 0xe0, 0xf6, 0x29, 0xf9, 0x53, 0x1d, 0xc1, 0xb1, 0x19, 0x7d, 0xdd, 0xc1, 0xec, 0x3f, 0xa3,
	0x89, 0x82, 0x7e, 0x29, 0xc1, 0xfd, 0x99, 0x76, 0x36, 0x45, 0x70, 0x03, 0xde, 0xe0, 0x57, 0xe1,
	0x12, 0xa6, 0xb7, 0x54, 0xb7, 0xc3, 0x9b, 0x27, 0xbe, 0x87, 0xf9, 0x4f, 0x9e, 0x56, 0xa4, 0x87,
	0x7b, 0x9b, 0xb3, 0x83, 0xcb, 0x8d, 0xb7, 0x60, 0x46, 0xf5, 0xc6, 0xbe, 0xb0, 0xc2, 0x67, 0x80,
	0xd7, 0x45, 0x15, 0x7d, 0x1f, 0x5f, 0x6f, 0x09, 0xd3, 0xdd, 0xd6, 0xe4, 0xed, 0xb2, 0xe6, 0xb9,
	0xf9, 0x6b, 0x83, 0xf3, 0x59, 0xff, 0x5d, 0xf0, 0x2d, 0xb8, 0xfd, 0x85, 0xf0, 0xb4, 0x9f, 0x39,
	0x72, 0x08, 0x4e, 0xf6, 0xf0, 0x32, 0xad, 0xc3, 0x09, 0x9e, 0xc1, 0xc3, 0x0e, 0xfb, 0x50, 0xef,
	0xb6, 0xf8, 0xc0, 0xf0, 0x76, 0xdb, 0x60, 0x78, 0xd6, 0x70, 0x82, 0xcf, 0xc1, 0xfb, 0x28, 0x88,
	0x2b, 0x32, 0xc1, 0x0f, 0xbb, 0xf7, 0x51, 0x79, 0x1e, 0x51, 0x7a, 0x98, 0x7a, 0x99, 0x95, 0xaa,
	0x19, 0xff, 0x1a, 0xbc, 0xc1, 0xba, 0xe8, 0xb7, 0x37, 0xd9, 0x4b, 0xe0, 0xae, 0xee, 0x02, 0x8e,
	0x46, 0xb1, 0xe2, 0xb0, 0x1f, 0xf8, 0x87, 0x82, 0x0f, 0x27, 0x37, 0x8e, 0xfe, 0x46, 0x5e, 0xfe,
	0x0b, 0x00, 0x00, 0xff, 0xff, 0x54, 0x57, 0x38, 0x17, 0x6d, 0x03, 0x00, 0x00,
}
